"$schema" = "https://starship.rs/config-schema.json"
add_newline = false
format = """[â•­â”€](dimmed white)$all$fill$time$line_break\
            [â•°â”€](dimmed white)$character"""

[character]
success_symbol = "[ï„¸](dimmed white)"
error_symbol = "[ó°§š](dimmedreloa white)"

[aws]
symbol = "îŒ½"
format = "\\[[$symbol($profile)(\\($region\\))(\\[$duration\\])]($style)\\]"

[azure]
disabled = true

[buf]
symbol = "ï’"
disabled = true

[bun]
format = "\\[[$symbol($version)]($style)\\]"

[c]
symbol = "î˜"
format = "\\[[$symbol($version(-$name))]($style)\\]"

[cmake]
format = "\\[[$symbol($version)]($style)\\]"

[cmd_duration]
format = "\\[[â± $duration]($style)\\]"

[cobol]
format = "\\[[$symbol($version)]($style)\\]"

[conda]
symbol = "ï„Œ"
format = "\\[[$symbol$environment]($style)\\]"

[crystal]
symbol = "î˜¯"
format = "\\[[$symbol($version)]($style)\\]"

[daml]
format = "\\[[$symbol($version)]($style)\\]"

[dart]
symbol = "î˜"
format = "\\[[$symbol($version)]($style)\\]"

[deno]
format = "\\[[$symbol($version)]($style)\\]"

[directory]
read_only = " ó°Œ¾"
[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ï€"
"Pictures" = "ï€¾"

[docker_context]
symbol = "ïŒˆ"
format = "\\[[$symbol$context]($style)\\]"

[elixir]
symbol = "î˜­"
format = "\\[[$symbol($version \\(OTP $otp_version\\))]($style)\\]"

[elm]
symbol = "î˜¬"
format = "\\[[$symbol($version)]($style)\\]"

[fennel]
symbol = "îš¯"
format = "\\[[$symbol($version)]($style)\\]"

[fossil_branch]
symbol = "ï˜"
format = "\\[[$symbol$branch]($style)\\]"

[git_branch]
symbol = "ï˜"
format = "\\[[$symbol$branch]($style)\\]"

[git_commit]
tag_symbol = " ï’"

[golang]
symbol = "î˜§"
format = "\\[[$symbol($version)]($style)\\]"

[guix_shell]
symbol = "ïŒ¥"
format = "\\[[$symbol]($style)\\]"

[haskell]
symbol = "î·"
format = "\\[[$symbol($version)]($style)\\]"

[haxe]
symbol = "î™¦"
format = "\\[[$symbol($version)]($style)\\]"

[hg_branch]
symbol = "ï˜"
format = "\\[[$symbol$branch]($style)\\]"

[hostname]
ssh_symbol = "î¬"

[java]
symbol = "î‰–"
format = "\\[[$symbol($version)]($style)\\]"

[julia]
symbol = "î˜¤"
format = "\\[[$symbol($version)]($style)\\]"

[kotlin]
symbol = "î˜´"
format = "\\[[$symbol($version)]($style)\\]"

[lua]
symbol = "î˜ "
format = "\\[[$symbol($version)]($style)\\]"

[memory_usage]
symbol = "ó°›"
format = "\\[$symbol[$ram( | $swap)]($style)\\]"

[meson]
symbol = "ó°”·"
format = "\\[[$symbol$project]($style)\\]"

[nim]
symbol = "ó°†¥"
format = "\\[[$symbol($version)]($style)\\]"

[nix_shell]
symbol = "ïŒ“"
format = "\\[[$symbol$state( \\($name\\))]($style)\\]"

[nodejs]
symbol = "îœ˜"
format = "\\[[$symbol($version)]($style)\\]"

[ocaml]
symbol = "î™º"
format = "\\[[$symbol($version)(\\($switch_indicator$switch_name\\))]($style)\\]"

[os]
format = "\\[[$symbol]($style)\\]"

[os.symbols]
Alpaquita = "îª¢"
Alpine = "ïŒ€"
AlmaLinux = "ïŒ"
Amazon = "ï‰°"
Android = "ï…»"
Arch = "ïŒƒ"
Artix = "ïŒŸ"
CentOS = "ïŒ„"
Debian = "ïŒ†"
DragonFly = "îŠ"
Emscripten = "ïˆ…"
EndeavourOS = "ï†—"
Fedora = "ïŒŠ"
FreeBSD = "ïŒŒ"
Garuda = "ó°›“"
Gentoo = "ïŒ"
HardenedBSD = "ó°Œ"
Illumos = "ó°ˆ¸"
Kali = "ïŒ§"
Linux = "ïŒš"
Mabox = "î¬©"
Macos = "ïŒ‚"
Manjaro = "ïŒ’"
Mariner = "ï‡"
MidnightBSD = "ï††"
Mint = "ïŒ"
NetBSD = "ï€¤"
NixOS = "ïŒ“"
OpenBSD = "ó°ˆº"
openSUSE = "ïŒ”"
OracleLinux = "ó°Œ·"
Pop = "ïŒª"
Raspbian = "ïŒ•"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
RockyLinux = "ïŒ«"
Redox = "ó°€˜"
Solus = "ó° ³"
SUSE = "ïŒ”"
Ubuntu = "ïŒ›"
Unknown = "ïˆ­"
Void = "ïŒ®"
Windows = "ó°²"

[package]
symbol = "ó°—"
format = "\\[[$symbol$version]($style)\\]"

[perl]
symbol = "î™¾"
format = "\\[[$symbol($version)]($style)\\]"

[php]
symbol = "î˜ˆ"
format = "\\[[$symbol($version)]($style)\\]"

[pijul_channel]
symbol = "ï˜"
format = "\\[[$symbol$channel]($style)\\]"

[python]
symbol = "îˆµ"
format = "\\[[${symbol}${pyenv_prefix}(${version})(\\($virtualenv\\))]($style)\\]"

[rlang]
symbol = "ó°Ÿ”"

[ruby]
symbol = "î‘"
format = "\\[[$symbol($version)]($style)\\]"

[rust]
symbol = "ó±˜—"
format = "\\[[$symbol($version)]($style)\\]"

[scala]
symbol = "îœ·"
format = "\\[[$symbol($version)]($style)\\]"

[swift]
symbol = "î•"
format = "\\[[$symbol($version)]($style)\\]"

[zig]
symbol = "îš©"
format = "\\[[$symbol($version)]($style)\\]"

[gradle]
symbol = "î™ "
format = "\\[[$symbol($version)]($style)\\]"

[dotnet]
format = "\\[[$symbol($version)(ğŸ¯ $tfm)]($style)\\]"

[erlang]
format = "\\[[$symbol($version)]($style)\\]"

[gcloud]
format = "\\[[$symbol$account(@$domain)(\\($region\\))]($style)\\]"

[git_status]
format = "([\\[$all_status$ahead_behind\\]]($style))"

[helm]
format = "\\[[$symbol($version)]($style)\\]"

[kubernetes]
disabled = false
symbol = "âˆ"
format = "\\[$symbol\\]"

[opa]
format = "\\[[$symbol($version)]($style)\\]"

[openstack]
format = "\\[[$symbol$cloud(\\($project\\))]($style)\\]"

[pulumi]
format = "\\[[$symbol$stack]($style)\\]"

[purescript]
format = "\\[[$symbol($version)]($style)\\]"

[raku]
format = "\\[[$symbol($version-$vm_version)]($style)\\]"

[red]
format = "\\[[$symbol($version)]($style)\\]"

[spack]
format = "\\[[$symbol$environment]($style)\\]"

[sudo]
format = "\\[[as $symbol]($style)\\]"

[terraform]
format = "\\[[$symbol$workspace]($style)\\]"

[time]
disabled = false
use_12hr = true
format = '[$time](bold dimmed)'

[username]
format = "\\[[$user]($style)\\]"

[vagrant]
format = "\\[[$symbol($version)]($style)\\]"

[vlang]
format = "\\[[$symbol($version)]($style)\\]"

[solidity]
format = "\\[[$symbol($version)]($style)\\]"
