[settings]
experimental = true
yes = true
status = { missing_tools = "always", show_env = false, show_tools = false }
trusted_config_paths = [
  "{{ get_env(name='HOME') }}/Github/shamubernetes/",
  "{{ get_env(name='HOME') }}/Github/kiliantyler/",
]
disable_hints = ["python_multi"]
idiomatic_version_file_enable_tools = ["node"]

#[plugins]
#devcontainer = "https://github.com/iloveitaly/asdf-devcontainer"
#trunk = "https://github.com/sdurrheimer/asdf-trunk"
#micro = "https://github.com/YR-ZR0/asdf-micro"
#topgrade = "https://github.com/kiliantyler/asdf-topgrade.git"
#aliae = "https://github.com/kiliantyler/asdf-aliae.git"
#coreutils = "https://github.com/kiliantyler/asdf-coreutils.git"
#atuin = "https://github.com/rzyns/asdf-atuin.git"
#git = "https://github.com/john-cai/asdf-git.git"

[tools]
1password-cli = "latest"
age = "latest"
awscli = "latest"
bun = "latest"
direnv = "latest"
editorconfig-checker = "latest"
# eza = "latest"
flux2 = "latest"
fzf = "latest"
goreleaser = "latest"
helm = "latest"
jq = "latest"
kubecolor = "latest"
kubectl = "latest"
node = "latest"
sops = "latest"
talosctl = "latest"
terraform-docs = "latest"
terraform = "latest"
terragrunt = "latest"
yamlfmt = "latest"
yarn = "latest"
yq = "latest"
zoxide = "latest"
atuin = "latest"
helmfile = "latest"
kustomize = "latest"
usage = "latest"
delta = "latest"

# Go tools
go = "latest"

# Python tools
python = "latest"
pipx = "latest"

# Rust tools
rust = "latest"
"cargo:eza" = "latest"
