[settings]
experimental = true
yes = true
status = { missing_tools = "always", show_env = false, show_tools = false }
trusted_config_paths = [
  "{{ get_env(name='HOME') }}/Github/shamubernetes/",
  "{{ get_env(name='HOME') }}/Github/kiliantyler/",
]
disable_hints = ["python_multi"]
idiomatic_version_file_enable_tools = ["node"]

[tools]
1password-cli = "latest"
act = "latest"
age = "latest"
atuin = "latest"
awscli = "latest"
bun = "latest"
chezmoi = "latest"
cilium-cli = "latest"
delta = "latest"
direnv = "latest"
dotenvx = "latest"
editorconfig-checker = "latest"
eza = { version = "latest", os = ["macos", "linux"] }
flux2 = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
goreleaser = "latest"
helm = "latest"
helmfile = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubecolor = "latest"
kubectl = "latest"
kubectx = "latest"
kustomize = "latest"
node = "latest"
python = "latest"
rust = "latest"
sops = "latest"
starship = "latest"
talosctl = "latest"
talhelper = "latest"
terraform = "latest"
terraform-docs = "latest"
terragrunt = "latest"
usage = "latest"
uv = "latest"
yamlfmt = "latest"
yarn = "latest"
yq = "latest"
zoxide = "latest"
